server:
    port: 8083
spring:
  application:
    name: likelion-websocket
  rabbitmq:
    username: admin
    password: abcde12# #default Password
    host: localhost # default host
    port: 5672      #default port
  ai:
    openai:
      api-key: ${OPEN_AI_KEY}
      chat:
        options:
          model: gpt-4.5-turbo
          temperature: 0.7
          max-tokens: 200

